# Site settings
title: Solo, a Jekyll Theme
tag_text: Solo
description: Solo is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s responsive.

# Build settings
markdown: kramdown
highlighter: pygments

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

exclude: ["README.md"]

